# Shared AWS credentials. Both analytics-service and evaluation-service envFrom this.
# Rotate here, restart both deployments, done.
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIAUJBLR6SHI3UB4GMH"
  AWS_SECRET_ACCESS_KEY: "SxiMEip1kUPBqiYzgzr+ZBQgBjlTDHciBAXmoHB6"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEA4aCXVzLXdlc3QtMiJGMEQCIHdhHV6jGOLkHyHjga7OAw21VLAuTN1wGBZ1W2aGaDw2AiAnHsDQN3UDzoLJjRaYm9AZYPCQ+u9F0rQ5NDHzPjX01Cq7AgjX//////////8BEAAaDDI5NDI5NjYxNDAzMCIMeV2yru2iCdWyUVmcKo8Ch1JR8zLW3w9PVbsgkSaEzqaZ/fbEY1x/ltI+MDh5/k+FaeOmS+7mlneFfAG4DOvt6kq7c8AQrC90qrIkb3BkU14cUVvz/2PrnDeyRhh2LC/ub6O0UwzXwTGKAI++wvkTdjI+T+xvvV9KYPa2cBl4VB7GL/KhYx70oUqfIbDv2v9B+r6UB8jztb4sPwroYVXxVY97f3T82zZbgknMRSGIlS0CAKmrkJUGV7JcOorGvppamf9sloH9VbPUgA9b213k+NHi7tC6vLpvnTRbcl5kMBgi5Mx9T8t14pT+p2vLhZNe3kystb6cIEzORGiB9FYrWAiJNz5aFM7hRUbILfuJwy9wBK8JKAYkTeMW8O9OejDIn6LRBjqeAXGoLcHP+qBoq4DciSCfJXT36VgGQ0rgDVUs/9Hd4nYsm8R1CaVKuu0xiLZrTldZC+VVySKh6wTTprRWYyPer+zHXeEhPbye08eVszgQ7oj7/muwxpxfmMRSxqSiShv7Bkwm3CmIaVxFnCBOkYS8qyzwaVK7zmL1IUhbbW1BADEIdDqq+uaqnuGovMuqqfPm0ivV3l3dTX2FQj9GDLqg"
