# Shared AWS credentials. Both analytics-service and evaluation-service envFrom this.
# Rotate here, restart both deployments, done.
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIAUJBLR6SHNCMTGXQC"
  AWS_SECRET_ACCESS_KEY: "tdm6hG/psnqZ8/nYTc4L5QkSduWwDEoNYtk/ts4l"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEAcaCXVzLXdlc3QtMiJHMEUCIAWiR6uZ2yTPZN2i0ZOgG0gluOa5QAA2hP88fl6TCgrCAiEAx5HoyXhgHMJMd190N8wrdNjeYtEeUoMS00xIyRicL/4quwII0P//////////ARAAGgwyOTQyOTY2MTQwMzAiDDu7xM+DsxfQjXAjtSqPAt5H+EA7ftHNFa28M/VTOWjTHL26k0qT+6PjfYF2LuLcv749VBq4u+GTAFEtEG0CVquMC15M6j4fPIJ/q06b93gMs5LcTetUAhvdBnyCHai4B/AZwDC01pECwVUUblAl9cZqXcgd+RuqMTHKxM98OM3HlsBpva8WNoqD4kSCkKiYZ5GVYGRt8v1IezYxcU+VKgizIJ5BF58B86i9cyBIOhDjv5X7g1u86VJdlBvdKGFtPNzLYLyD9/m/a4Dj4/CQFDfbTsJkBswaNVbDVwbfxv7+UeEb7ckLGvEeTuXhxaRKMuHWpb3cyxFwWA43V50eOk2U+tyFWfjgugQBKK1jt1txqpObKWRJe8Il83XSxuIw6q7o0AY6nQFhsIA6qYrVrw29xeMhJNPAhvjqig1iX2HDanG1vYDpwcy9aJ6oxcL8Z8H3z8Q4mB5qq6y61lBCGf4ZSek+w/x9WGCRG3+ORGHITdtmeUOrCLfZvGFBq4x0xSk3yJKVcqe3JHKZXKmGD2ONMKZfd7Vrk0A9LNWrOKccbS6gWFI2pzexVUTinRxYiISQIMzChmaWpgRFKnYqqX+5wqDD"
