# Shared AWS credentials. Both analytics-service and evaluation-service envFrom this.
# Rotate here, restart both deployments, done.
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: togglemaster
type: Opaque
stringData:
#  AWS_ACCESS_KEY_ID: 
#  AWS_SECRET_ACCESS_KEY: 
#  AWS_SESSION_TOKEN: 
