---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_da8a1a3671b2f318eecc11e2ce059f30d2c64574d482d7a01ae336a68a53f54a"
