---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_0aa1723723ae0f63ec93f3fddc0b81e34836cd4ca96d6eb68ba7211fd2ac33fd"
