---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/294296614030/pompei-fiap-sqs-fila"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
