#!/usr/bin/env bash
# Install the nginx ingress controller (provisions an AWS ELB) and generate a
# nip.io-based Ingress so the services are reachable with zero DNS setup.
#
# *.toggle.local does not resolve on EKS. nip.io maps <anything>.<IP>.nip.io to
# <IP>, so we resolve the ELB to an IP and build hosts like:
#   auth.<ip>.nip.io  flags.<ip>.nip.io  ... etc.
#
# NOTE: the ELB's IP can change (it's fronted by a DNS name with multiple/rotating
# IPs). If connectivity breaks later, just re-run this script to regenerate.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NS_INGRESS=ingress-nginx
NS=togglemaster

echo ">> Installing nginx ingress controller (AWS)"
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/aws/deploy.yaml

echo ">> Waiting for controller to be available"
kubectl -n "$NS_INGRESS" wait --for=condition=available deployment/ingress-nginx-controller --timeout=240s

echo ">> Waiting for the ELB hostname to be assigned"
ELB=""
for _ in $(seq 1 30); do
  ELB="$(kubectl -n "$NS_INGRESS" get svc ingress-nginx-controller \
    -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
  [ -n "$ELB" ] && break
  sleep 10
done
[ -n "$ELB" ] || { echo "ELB hostname not ready; check the ingress-nginx svc"; exit 1; }
echo "   ELB: $ELB"

echo ">> Resolving ELB to an IP for nip.io"
IP="$(dig +short "$ELB" | grep -Eo '^[0-9.]+$' | head -n1)"
[ -n "$IP" ] || { echo "Could not resolve $ELB to an IP"; exit 1; }
echo "   IP: $IP  ->  hosts will be <svc>.$IP.nip.io"

OUT="$SCRIPT_DIR/ingress-nip.generated.yaml"
cat > "$OUT" <<YAML
# Generated by 03-ingress-nip.sh — do not edit by hand. Re-run the script to refresh.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: togglemaster-ingress
  namespace: $NS
spec:
  ingressClassName: nginx
  rules:
$(for entry in "auth:auth-service:8001" "flags:flag-service:8002" \
               "targeting:targeting-service:8003" "eval:evaluation-service:8004" \
               "analytics:analytics-service:8005"; do
    sub="${entry%%:*}"; rest="${entry#*:}"; svc="${rest%%:*}"; port="${rest##*:}"
    printf '    - host: %s.%s.nip.io\n' "$sub" "$IP"
    printf '      http:\n        paths:\n          - path: /\n            pathType: Prefix\n'
    printf '            backend:\n              service:\n                name: %s\n                port:\n                  number: %s\n' "$svc" "$port"
  done)
YAML

echo ">> Applying generated ingress: $OUT"
kubectl apply -f "$OUT"

echo
echo ">> Reachable at:"
echo "   curl http://auth.$IP.nip.io/health"
echo "   curl http://flags.$IP.nip.io/health"
echo "   curl http://targeting.$IP.nip.io/health"
echo "   curl http://eval.$IP.nip.io/health"
echo "   curl http://analytics.$IP.nip.io/health"
