---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_USER: targeting_db
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: targeting_db
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgres://targeting_db:123456@targeting-db:5432/targeting_db?sslmode=disable"
