---
apiVersion: v1
kind: Service
metadata:
  name: flag-db
  namespace: togglemaster
spec:
  clusterIP: None
  selector:
    app: flag-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flag-db
  namespace: togglemaster
spec:
  serviceName: flag-db
  replicas: 1
  selector:
    matchLabels:
      app: flag-db
  template:
    metadata:
      labels:
        app: flag-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: flag-db-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "flag_db", "-d", "flag_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "flag_db", "-d", "flag_db"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: init
          configMap:
            name: flag-db-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
