#!/usr/bin/env bash
# Install the nginx ingress controller on OKE (provisions an OCI Flexible Load
# Balancer) and generate a nip.io-based Ingress — same host-based routing as the
# EKS setup (auth./flags./targeting./eval./analytics.<IP>.nip.io).
#
# Unlike AWS (which gives the LB a hostname), OCI assigns the LB a public IP
# directly, so nip.io is even simpler here: no dig needed.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NS_INGRESS=ingress-nginx
NS=togglemaster

echo ">> Installing nginx ingress controller (cloud/OCI provider)"
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml

echo ">> Waiting for controller"
kubectl -n "$NS_INGRESS" wait --for=condition=available deployment/ingress-nginx-controller --timeout=300s

echo ">> Waiting for the OCI load balancer public IP"
IP=""
for _ in $(seq 1 40); do
  IP="$(kubectl -n "$NS_INGRESS" get svc ingress-nginx-controller \
    -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)"
  [ -n "$IP" ] && break
  sleep 10
done
[ -n "$IP" ] || { echo "LB IP not ready; check: kubectl -n $NS_INGRESS get svc"; exit 1; }
echo "   LB IP: $IP  ->  hosts will be <svc>.$IP.nip.io"

OUT="$SCRIPT_DIR/ingress-nip.generated.yaml"
cat > "$OUT" <<YAML
# Generated by oci/04-ingress-nip.sh — do not edit by hand. Re-run to refresh.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: togglemaster-ingress
  namespace: $NS
spec:
  ingressClassName: nginx
  rules:
$(for entry in "auth:auth-service:8001" "flags:flag-service:8002" \
               "targeting:targeting-service:8003" "eval:evaluation-service:8004" \
               "analytics:analytics-service:8005"; do
    sub="${entry%%:*}"; rest="${entry#*:}"; svc="${rest%%:*}"; port="${rest##*:}"
    printf '    - host: %s.%s.nip.io\n' "$sub" "$IP"
    printf '      http:\n        paths:\n          - path: /\n            pathType: Prefix\n'
    printf '            backend:\n              service:\n                name: %s\n                port:\n                  number: %s\n' "$svc" "$port"
  done)
YAML

echo ">> Applying generated ingress: $OUT"
kubectl apply -f "$OUT"

cat <<EOF

>> Reachable at:
   curl http://auth.$IP.nip.io/health
   curl http://flags.$IP.nip.io/health
   curl http://targeting.$IP.nip.io/health
   curl http://eval.$IP.nip.io/health
   curl http://analytics.$IP.nip.io/health

   End-to-end flag eval (mirrors the EKS test):
   curl "http://eval.$IP.nip.io/evaluate?user_id=user-123&flag_name=enable-new-dashboard"
EOF
