---
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_USER: auth_db
  POSTGRES_PASSWORD: "123456"
  POSTGRES_DB: auth_db
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  MASTER_KEY: "admin-secreto-123"
  DATABASE_URL: "postgres://auth_db:123456@auth-db:5432/auth_db?sslmode=disable"
